package com.ulisfintech.telrpay.ui;

interface APIConstant {

    String X_USERNAME = "074E1F9E8KF87HJDF8DF09DDD3A377760";
    String X_PASSWORD = "54607074E1F9DE8KF87HJDF8DF09DDD";

    String ORDER_STATUS_PENDING = "Pending";
    String ORDER_STATUS_AUTHORISED = "AUTHORISED";
    String ORDER_STATUS_FAILED = "Failed";
    String ORDER_STATUS_CANCELLED = "CANCELLED";


}
